export const TitleClr = "#EFEFEF"
export const TabActiveClr = "#1d9bf0"
export const BackgroundClr = "#171717"
export const TopNavBarClr = "#141414"
export const PriceClr = "#ff751f"
export const MarketClr = "#0081ff"
export const VolumeClr = "#ffc001"
export const SearchTxtClr = "#4b4e4f"